#!/bin/bash

script_dir=/ooi/bin

# Environment

export UFRAME_HOME=/
export AWIPS_HOME=$UFRAME_HOME
export CONSOLE_LOGLEVEL=INFO
export EDEX_HOME=$UFRAME_HOME/edex
export HOSTNAME=$(hostname)
export ALLOW_ARCHIVE_DATA=false
export AMQP_SPEC=$UFRAME_HOME/python/share/amqp/amqp.0-10.xml
export SKIP_RPM_CHECK=1
export JAVA_INSTALL=$JAVA_HOME

export EDEX_RUN_MODE=${EDEX_RUN_MODE:=ooi}

START_ARGS="$START_ARGS $EDEX_RUN_MODE"
${EDEX_HOME}/bin/start.sh $START_ARGS

